version: '3.8'

services:
  app:
    container_name: dragon-app
    image: dragon-app
    build: .
    ports:
      - "8080:8080"  
    networks:
      - app-network
    env_file:
      - ./.env 
    restart: unless-stopped  
networks:
  app-network:
    driver: bridge  
